const MSW_LIST_KEY = "__MSW_LOCAL_LIST__";
const MSW_ALL_STATUS = "__MSW_ALL_STATUS__";
const MSW_GLOBAL_STATUS = "__MSW_GLOBAL_STATUS__";
const MSW_REQUEST_TIME = "__MSW_REQUEST_TIME__";
const MSW_REQUEST_FAIL_RATIO = "__MSW_REQUEST_FAIL_RATIO__";
const MSW_RESPONSE_STATUS_CODE = "__MSW_RESPONSE_STATUS_CODE__";

export {
  MSW_LIST_KEY,
  MSW_ALL_STATUS,
  MSW_GLOBAL_STATUS,
  MSW_REQUEST_TIME,
  MSW_REQUEST_FAIL_RATIO,
  MSW_RESPONSE_STATUS_CODE,
};
